broker: 'amqp://guest:guest@rabbitmq:5672/'
default_queue: celery
celery_message: 2
concurrency: 2000

# result_backend: 'redis://138.85.229.97:6379'
result_backend: 'redis://redis:6379'
results_expire_in: 3600000

amqp:
  binding_key: celery
  exchange: machinery_exchange
  exchange_type: direct
  prefetch_count: 2000
